name: 'Setup Common Environment'
description: 'Setup environment with repository checkout, tools installation, and tmate debugging'

inputs:
  repository:
    description: 'Repository to checkout (e.g., syntasso/kratix)'
    required: false
    default: ''
  ref:
    description: 'Reference to checkout (commit sha, branch, etc.)'
    required: false
    default: ''
  path:
    description: 'Path to checkout repository into'
    required: false
    default: ''
  ssh_key:
    description: 'SSH key for private repository access'
    required: false
    default: ''
  submodules:
    description: 'Whether to checkout submodules'
    required: false
    default: 'false'
  submodule_repository:
    description: 'Submodule repository to checkout (e.g., syntasso/kratix)'
    required: false
    default: ''
  submodule_ref:
    description: 'Reference to checkout for submodule (commit sha, branch, etc.)'
    required: false
    default: ''
  submodule_path:
    description: 'Path to checkout submodule repository into'
    required: false
    default: ''
  ssh_session:
    description: 'Whether to enable tmate ssh debugging session (true/false)'
    required: false
    default: 'false'
  tools_base_path:
    description: 'Base path where tools will be installed and cached'
    required: false
    default: 'kratix'

runs:
  using: 'composite'
  steps:
    - name: Checkout parameterized repository
      if: "${{ inputs.repository != '' }}"
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        path: ${{ inputs.path }}
        ssh-key: ${{ inputs.ssh_key }}
        submodules: ${{ inputs.submodules }}

    - name: Checkout submodule repository
      if: "${{ inputs.submodule_repository != '' && inputs.submodule_ref != '' }}"
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.submodule_repository }}
        ref: ${{ inputs.submodule_ref }}
        path: ${{ inputs.submodule_path }}

    - name: Start tmate ssh debugging session
      if: "${{ inputs.ssh_session == 'true' }}"
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
        detached: true

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24
        check-latest: true
        cache-dependency-path: ${{ inputs.path }}/go.sum

    - name: Prepare cache control variables
      shell: bash
      run: |
        cd "${{ inputs.tools_base_path }}"
        echo "GO_VERSION=$(go env GOVERSION)" >> "$GITHUB_ENV"
        echo "KUSTOMIZE_VERSION=$(grep -E '^KUSTOMIZE_VERSION[[:space:]]*\?=' Makefile | tail -n1 | awk '{print $3}')" >> "$GITHUB_ENV"
        echo "CONTROLLER_TOOLS_VERSION=$(grep -E '^CONTROLLER_TOOLS_VERSION[[:space:]]*\?=' Makefile | tail -n1 | awk '{print $3}')" >> "$GITHUB_ENV"

    - name: Cache build tools
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.tools_base_path }}/bin/kustomize*
          ${{ inputs.tools_base_path }}/bin/controller-gen*
        key: ${{ runner.os }}-kratix-tools-${{ env.GO_VERSION }}-${{ env.KUSTOMIZE_VERSION }}-${{ env.CONTROLLER_TOOLS_VERSION }}

    - name: Install build tools
      shell: bash
      run: |
        cd "${{ inputs.tools_base_path }}"
        make controller-gen
        make kustomize

    - name: Install Kind
      uses: helm/kind-action@v1
      with:
        install_only: true
        version: v0.29.0

    - name: Setup Flux CLI
      uses: fluxcd/flux2/action@main
      with:
        version: '2.4.0'
