name: 'Setup Common Environment'
description: 'Setup common environment for SKE tests including Go, Kind, and repository checkouts'

inputs:
  ske_sha:
    description: 'Commit sha of enterprise-kratix'
    required: true
  sha:
    description: 'Commit sha of Kratix'
    required: false
    default: ''
  enterprise_kratix_deploy_key:
    description: 'SSH key for enterprise-kratix repository'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check out enterprise kratix
      uses: actions/checkout@v4
      with:
        repository: syntasso/enterprise-kratix
        ssh-key: ${{ inputs.enterprise_kratix_deploy_key }}
        ref: ${{ inputs.ske_sha }}
        path: enterprise-kratix
        submodules: recursive

    - name: Checkout out kratix into enterprise kratix
      if: "${{ inputs.sha != '' }}"
      uses: actions/checkout@v4
      with:
        repository: syntasso/kratix
        ref: ${{ inputs.sha }}
        path: enterprise-kratix/read-only-kratix

    - name: Start tmate ssh debugging session
      if: "${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ssh_session }}"
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
        detached: true

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23
        check-latest: true

    - name: Install Kind
      uses: helm/kind-action@v1
      with:
        install_only: true
        version: v0.29.0

    - name: Setup Flux CLI
      uses: fluxcd/flux2/action@main
      with:
        version: '2.4.0' 