name: Docker Build (buildx)
description: Build images with docker buildx
inputs:
  tag:
    description: Primary image tag
    required: true
  dockerfile:
    description: Dockerfile path
    required: true
  context:
    description: Build context path
    required: true
  platforms:
    description: Target platforms
    required: false
    default: linux/amd64,linux/arm64
  builder:
    description: Buildx builder name
    required: false
    default: ci-image-builder
  push:
    description: Push images
    required: false
    default: "true"
  load:
    description: Load image into local docker
    required: false
    default: "false"
  extra_tags:
    description: Additional tags (space separated)
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Build image
      shell: bash
      run: |
        set -euo pipefail

        if [[ "${{ inputs.push }}" == "true" && "${{ inputs.load }}" == "true" ]]; then
          echo "Only one of push or load can be true" >&2
          exit 1
        fi

        if docker buildx inspect "${{ inputs.builder }}" >/dev/null 2>&1; then
          docker buildx use "${{ inputs.builder }}"
        else
          docker buildx create --name "${{ inputs.builder }}" --use
        fi

        tags=("-t" "${{ inputs.tag }}")
        if [[ -n "${{ inputs.extra_tags }}" ]]; then
          for t in ${{ inputs.extra_tags }}; do
            tags+=("-t" "$t")
          done
        fi

        args=(--builder "${{ inputs.builder }}" --platform "${{ inputs.platforms }}" --file "${{ inputs.dockerfile }}")
        if [[ "${{ inputs.push }}" == "true" ]]; then
          args+=(--push)
        elif [[ "${{ inputs.load }}" == "true" ]]; then
          args+=(--load)
        fi

        docker buildx build "${args[@]}" "${tags[@]}" "${{ inputs.context }}"
