name: enterprise-kratix # separate workflow to integrate faster

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'Commit sha of Kratix'
        required: true
      message:
        description: 'Commit message'
        required: false
jobs:
  ske-upgrade-test:
    runs-on: ubuntu-latest
    # needs: [ unit-tests-and-lint ]
    steps:
      - name: Check out enterprise kratix
        uses: actions/checkout@v4
        with:
          repository: syntasso/enterprise-kratix
          ssh-key: ${{ secrets.ENTERPRISE_KRATIX_DEPLOY_KEY_READ_PUSH }}
      - name: Checkout out kratix into enterprise kratix
        uses: actions/checkout@v4
        with:
          repository: syntasso/kratix
          ref: ${{ github.event.inputs.sha }}
          path: ready-only-kratix
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          check-latest: true
      - name: Install Kind
        uses: helm/kind-action@v1
        with:
          install_only: true
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
        with:
          version: '2.4.0'
      - name: Install vCluster CLI
        uses: loft-sh/setup-vcluster@main
      - name: ske-upgrade
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          ./scripts/run-ske-upgrade-test-in-kind.sh
            
