name: enterprise-kratix # separate workflow to integrate faster

on:
  pull_request:
    branches: [ "main" ]
#  workflow_dispatch:
#    inputs:
#      sha:
#        description: 'Commit sha of Kratix'
#        required: true
#      message:
#        description: 'Commit message'
#        required: false
jobs:
  ske-upgrade-test:
    runs-on: ubuntu-latest
    # needs: [ unit-tests-and-lint ]
    steps:
      - name: Check out enterprise kratix
        uses: actions/checkout@v4
        with:
          repository: syntasso/enterprise-kratix
          ssh-key: ${{ secrets.ENTERPRISE_KRATIX_DEPLOY_KEY_READ_PUSH }}
      - name: Checkout out kratix into enterprise kratix
        uses: actions/checkout@v4
        with:
          repository: syntasso/kratix
#          ref: ${{ github.event.inputs.sha }}
          ref: 09bb931aec3031e07d9810da52af56c0e31c19d7
          path: ready-only-kratix
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          check-latest: true
      - name: Install Kind
        uses: helm/kind-action@v1
        with:
          install_only: true
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
        with:
          version: '2.4.0'
      - name: Install vCluster CLI
        uses: loft-sh/setup-vcluster@main
      - name: ske-upgrade
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_RELEASE_CREATOR_TOKEN }}
        run: |
          ls
          pushd read-only-kratix
          ls
          make help
          popd
          # ./scripts/run-ske-upgrade-test-in-kind.sh
            
