name: enterprise-kratix # separate workflow to integrate faster

on:
  pull_request:
    branches: [ "main" ]
#  workflow_dispatch:
#    inputs:
#      sha:
#        description: 'Commit sha of Kratix'
#        required: true
#      message:
#        description: 'Commit message'
#        required: false
jobs:
  ske-upgrade-test:
    runs-on: ubuntu-latest
    # needs: [ unit-tests-and-lint ]
    steps:
      - name: Check out enterprise kratix
        uses: actions/checkout@v4
        with:
          repository: syntasso/enterprise-kratix
          ssh-key: ${{ secrets.ENTERPRISE_KRATIX_DEPLOY_KEY_READ_PUSH }}
      - name: Checkout out kratix into enterprise kratix
        uses: actions/checkout@v4
        with:
          repository: syntasso/kratix
          ref: ${{ github.event.inputs.sha }}
          path: read-only-kratix
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          check-latest: true
      - name: Install Kind
        uses: helm/kind-action@v1
        with:
          install_only: true
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
        with:
          version: '2.4.0'
      - name: Install vCluster CLI
        uses: loft-sh/setup-vcluster@main
      - name: Upgrade tests
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_RELEASE_CREATOR_TOKEN }}
        run: ./scripts/run-ske-upgrade-test-in-kind.sh


  ske-backstage-test:
    runs-on: ubuntu-latest
    # needs: [ unit-tests-and-lint ]
    steps:
      - name: Check out enterprise kratix
        uses: actions/checkout@v4
        with:
          repository: syntasso/enterprise-kratix
          ssh-key: ${{ secrets.ENTERPRISE_KRATIX_DEPLOY_KEY_READ_PUSH }}
      - name: Checkout out kratix into enterprise kratix
        uses: actions/checkout@v4
        with:
          repository: syntasso/kratix
          ref: ${{ github.event.inputs.sha }}
          path: read-only-kratix
      - name: Checkout out backstage
        uses: actions/checkout@v4
        with:
          repository: syntasso/backstage
          ssh-key: ${{ secrets.BACKSTAGE_REPO_DEPLOY_KEY }}
          path: backstage-plugins
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          check-latest: true
      - name: Install Kind
        uses: helm/kind-action@v1
        with:
          install_only: true
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
        with:
          version: '2.4.0'
      - name: Install vCluster CLI
        uses: loft-sh/setup-vcluster@main
      - name: Install Backstage plugins
        run: |
          pushd backstage-plugins/plugins/ske-backend
            yarn install
          popd
          pushd backstage-plugins/plugins/ske-frontend
            yarn install
          popd
      - name: Backstage tests
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_RELEASE_CREATOR_TOKEN }}
        run: ./scripts/test-ske-with-backstage-in-kind.sh

  update-read-only-kratix:
    runs-on: ubuntu-latest
    needs: [ ske-backstage-test,ske-upgrade-test ]
    steps:
      - name: Check out enterprise kratix
        uses: actions/checkout@v4
        env:
          KRATIX_COMMIT_SHA: ${{ github.event.inputs.sha }}
        with:
          repository: syntasso/enterprise-kratix
          ssh-key: ${{ secrets.ENTERPRISE_KRATIX_DEPLOY_KEY_READ_PUSH }}
        run: scripts/update-read-only-kratix-commit-sha.sh
