name: test-ske

on:
  workflow_dispatch:
    inputs:
      ssh_session:
        type: boolean
        description: 'Run the build with tmate debugging.'
        required: false
        default: false
      sha:
        description: 'Commit sha of Kratix'
        required: false
        type: string
      ske_sha:
        description: 'Commit sha of enterprise-kratix'
        required: false
        type: string
  workflow_call:
    inputs:
      sha:
        description: 'Commit sha of Kratix'
        required: false
        type: string
      ske_sha:
        description: 'Commit sha of enterprise-kratix'
        required: false
        type: string

jobs:
  ske-quick-start-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Common Environment
        uses: ./.github/actions/setup-common
        with:
          ske_sha: ${{ github.event.inputs.ske_sha }}
          sha: ${{ github.event.inputs.sha }}
          enable_tmate: 'true'
      - name: Quick start tests
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_RELEASE_CREATOR_TOKEN }}
        run: |
          cd ske-quick-start-installer/
          make system-test

  ske-upgrade-and-oss-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Common Environment
        uses: ./.github/actions/setup-common
        with:
          ske_sha: ${{ github.event.inputs.ske_sha }}
          sha: ${{ github.event.inputs.sha }}
          enable_flux: 'true'
      - name: Install vCluster CLI
        uses: loft-sh/setup-vcluster@main
      - name: Upgrade tests
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_RELEASE_CREATOR_TOKEN }}
        run: ./scripts/run-ske-test-in-kind.sh

  ske-backstage-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Common Environment
        uses: ./.github/actions/setup-common
        with:
          ske_sha: ${{ github.event.inputs.ske_sha }}
          sha: ${{ github.event.inputs.sha }}
          enable_flux: 'true'
      - name: Setup Backstage Environment
        uses: ./.github/actions/setup-backstage
      - name: Backstage tests
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_RELEASE_CREATOR_TOKEN }}
          DOCKER_PRUNE: "true"
        run: |
          # deleting unnecessary files to gain some hard disk space
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf /usr/local/lib/android
          ./scripts/test-ske-with-backstage-in-kind.sh

  ske-operator:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Common Environment
        uses: ./.github/actions/setup-common
        with:
          ske_sha: ${{ github.event.inputs.ske_sha }}
          sha: ${{ github.event.inputs.sha }}
          enable_tmate: 'true'
          enable_flux: 'true'
      - name: Run make test-e2e-ci
        run: |
          make test-e2e-ci
        working-directory: ske-operator
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
          SKE_LICENSE_TOKEN: ${{ secrets.SKE_LICENSE_TOKEN }}

  ske-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Common Environment
        uses: ./.github/actions/setup-common
        with:
          ske_sha: ${{ github.event.inputs.ske_sha }}
          sha: ${{ github.event.inputs.sha }}
          enable_tmate: 'true'
          enable_flux: 'true'
      - name: Run make test-e2e-ci
        run: |
          make test-e2e-ci
        working-directory: ske-cli
        env:
          SKE_LICENSE_TOKEN: ${{ secrets.SKE_LICENSE_TOKEN }}
          KRATIX_DEVELOPER: true

